#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - path: /etc/systemd/system/solr.service
    content: |
        [Unit]
        Description=Solr
        Requires=docker.service
        After=docker.service

        [Service]
        EnvironmentFile=/etc/default/solr
        Restart=always
        ExecStartPre=-/usr/bin/docker stop %n
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n \
            -p 8983:8983 \
            -e ZK_HOST=${ZK_HOST} \
            -e SOLR_HOST=${SOLR_HOST} \
            -e SOLR_HEAP=${SOLR_HEAP} \
            -e ENABLE_REMOTE_JMX_OPTS=true \
            solr:8.6
        ExecStop=-/usr/bin/curl -ksfL \
          "http://localhost8983/solr/admin/collections?action=DELETENODE&node=${SOLR_HOST}:8983_solr"

        [Install]
        WantedBy=local.target
  - path: /opt/solr-env.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      ZK_HOST=$(aws ec2 describe-instances --region eu-west-1 --instance-ids \
        $(aws autoscaling describe-auto-scaling-instances --region eu-west-1 --output text \
          --query "AutoScalingInstances[?AutoScalingGroupName=='zookeeper'].InstanceId") \
      --query "Reservations[].Instances[].PrivateIpAddress" | jq -r '.[]' | awk 'ORS=":2181,"' | sed 's/.$//')
      SOLR_HEAP_MB=$(awk '/MemTotal/ { printf "%.0f", $2/1024/2 }' /proc/meminfo)

      # write solr env
      echo "ZK_HOST=${ZK_HOST}"
      echo "SOLR_HEAP=${SOLR_HEAP_MB}m"
      echo "SOLR_HOST=$(hostname)"
  - path: /opt/check-zookeeper.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      source /opt/solr-env.sh
      while  ! echo "ruok" | nc -w 1 ${ZK_HOST%%:*} 2181
      do
          echo "Waiting for Zookeeper ${ZK_HOST%%:*} to be up and running"
          sleep 1
      done
      echo "Zookeeper ready at ${ZK_HOST%%:*} ..."

runcmd:
  - /opt/solr-env.sh > /etc/default/solr
  - systemctl enable solr
  - /opt/check-zookeeper.sh
  - systemctl start solr
