#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [recurse_array]

write_files:
  - path: /etc/solr/solr.xml
    content: |
      <?xml version="1.0" encoding="UTF-8" ?>
      <solr>
        <int name="maxBooleanClauses">$${solr.max.booleanClauses:1024}</int>
        <str name="sharedLib">$${solr.sharedLib:}</str>
        <str name="allowPaths">$${solr.allowPaths:}</str>
        <solrcloud>
          <str name="host">$${host:}</str>
          <int name="hostPort">$${solr.port.advertise:0}</int>
          <str name="hostContext">$${hostContext:solr}</str>
          <bool name="genericCoreNodeNames">$${genericCoreNodeNames:true}</bool>
          <int name="zkClientTimeout">$${zkClientTimeout:30000}</int>
          <int name="distribUpdateSoTimeout">$${distribUpdateSoTimeout:600000}</int>
          <int name="distribUpdateConnTimeout">$${distribUpdateConnTimeout:60000}</int>
          <str name="zkCredentialsProvider">$${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>
          <str name="zkACLProvider">$${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>
        </solrcloud>
        <shardHandlerFactory name="shardHandlerFactory"
          class="HttpShardHandlerFactory">
          <int name="socketTimeout">$${socketTimeout:600000}</int>
          <int name="connTimeout">$${connTimeout:60000}</int>
          <str name="shardsWhitelist">$${solr.shardsWhitelist:}</str>
        </shardHandlerFactory>
        <metrics enabled="$${metricsEnabled:true}"/>
        <tracerConfig name="tracerConfig" class="org.apache.solr.jaeger.JaegerTracerConfigurator">
          <str name="agentHost">localhost</str>
          <int name="agentPort">6831</int>
          <bool name="logSpans">true</bool>
          <int name="flushInterval">1000</int>
          <int name="maxQueueSize">10000</int>
        </tracerConfig>
      </solr>

  - path: /etc/systemd/system/solr.service
    content: |
        [Unit]
        Description=Solr
        Requires=docker.service
        After=docker.service

        [Service]
        EnvironmentFile=/etc/default/solr
        Restart=always
        ExecStartPre=-/usr/bin/docker stop %n
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n \
            -p 8983:8983 \
            -v /etc/solr/solr.xml:/opt/solr/server/solr/solr.xml \
            -v /etc/solr/jaeger-core.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jaeger-core.jar \
            -v /etc/solr/jaeger-thrift.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jaeger-thrift.jar \
            -v /etc/solr/libthrift.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/libthrift.jar \
            -e ZK_HOST=$${ZK_HOST} \
            -e SOLR_HOST=$${SOLR_HOST} \
            -e SOLR_HEAP=$${SOLR_HEAP} \
            -e ENABLE_REMOTE_JMX_OPTS=true \
            solr:${solr_version}
        ExecStop=-/usr/bin/curl -ksfL \
          "http://localhost8983/solr/admin/collections?action=DELETENODE&node=$${SOLR_HOST}:8983_solr"

        [Install]
        WantedBy=local.target
  - path: /etc/systemd/system/solr-prometheus-exporter.service
    content: |
        [Unit]
        Description=Solr Prometheus Exporter
        Requires=solr.service
        After=solr.service

        [Service]
        EnvironmentFile=/etc/default/solr
        Restart=always
        ExecStartPre=-/usr/bin/docker stop %n
        ExecStartPre=-/usr/bin/docker rm %n
        ExecStart=/usr/bin/docker run --rm --name %n \
            -p 9854:9854 \
            solr:${solr_version} /opt/solr/contrib/prometheus-exporter/bin/solr-exporter \
              -p 9854 \
              -z $${ZK_HOST} \
              -b http://$${SOLR_HOST}:8983/solr \
              -f /opt/solr/contrib/prometheus-exporter/conf/solr-exporter-config.xml \
              -n 4

        [Install]
        WantedBy=local.target
  - path: /opt/solr-env.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      ZK_HOST=$(aws ec2 describe-instances --region eu-west-1 --instance-ids \
        $(aws autoscaling describe-auto-scaling-instances --region eu-west-1 --output text \
          --query "AutoScalingInstances[?AutoScalingGroupName=='zookeeper'].InstanceId") \
      --query "Reservations[].Instances[].PrivateIpAddress" | jq -r '.[]' | awk 'ORS=":2181,"' | sed 's/.$//')
      SOLR_HEAP_MB=$(awk '/MemTotal/ { printf "%.0f", $2/1024/2 }' /proc/meminfo)

      # write solr env
      cat << EOF > /etc/default/solr
      ZK_HOST=$${ZK_HOST}
      SOLR_HEAP=$${SOLR_HEAP_MB}m
      SOLR_HOST=$(hostname)
      EOF
  - path: /opt/check-zookeeper.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      source /opt/solr-env.sh
      while  ! echo "ruok" | nc -w 1 $${ZK_HOST%%:*} 2181
      do
          echo "Waiting for Zookeeper $${ZK_HOST%%:*} to be up and running"
          sleep 1
      done
      echo "Zookeeper ready at $${ZK_HOST%%:*} ..."

runcmd:
  - curl -sfLo /etc/solr/jaeger-core.jar https://repo1.maven.org/maven2/io/jaegertracing/jaeger-core/1.8.0/jaeger-core-1.8.0.jar
  - curl -sfLo /etc/solr/jaeger-thrift.jar https://repo1.maven.org/maven2/io/jaegertracing/jaeger-thrift/1.8.0/jaeger-thrift-1.8.0.jar
  - curl -sfLo /etc/solr/libthrift.jar https://repo1.maven.org/maven2/org/apache/thrift/libthrift/0.16.0/libthrift-0.16.0.jar

  - /opt/solr-env.sh
  - systemctl enable solr
  - systemctl enable solr-prometheus-exporter
  - /opt/check-zookeeper.sh

  - systemctl start solr
  - systemctl start solr-prometheus-exporter
